---
name: test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version:
          - 12
          - 14
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Normalize line endings
        run: |
          git config --global core.autocrlf input
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npm run lint
      - run: npm test
