---
name: "test"

on:
  - "push"
  - "pull_request"

jobs:
  test:
    name: "Test on node ${{ matrix.node_version }} and ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        node_version:
          - 16
          - 18
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macOS-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Use Node.js ${{ matrix.node_version }}"
        uses: "actions/setup-node@v3"
        with:
          node-version: "${{ matrix.node_version }}"
      - run: "npm ci"
      - run: "npm run lint"
      - run: "npm test"
      - name: "release"
        uses: "softprops/action-gh-release@v1"
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          draft: true
